/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApprovalAction } from '../model/approvalAction';
import { BooleanResponse } from '../model/booleanResponse';
import { CalendarEntity } from '../model/calendarEntity';
import { CalendarResponseDto } from '../model/calendarResponseDto';
import { OpenClosedRequestNumberResponse } from '../model/openClosedRequestNumberResponse';
import { Pageable } from '../model/pageable';
import { PagedResponseUserRequestResponseDto } from '../model/pagedResponseUserRequestResponseDto';
import { SaveCalendarEntityRequestDto } from '../model/saveCalendarEntityRequestDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CalendarService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCalendarEntity(id: string, observe?: 'body', reportProgress?: boolean): Observable<CalendarResponseDto>;
    public deleteCalendarEntity(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CalendarResponseDto>>;
    public deleteCalendarEntity(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CalendarResponseDto>>;
    public deleteCalendarEntity(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteCalendarEntity.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CalendarResponseDto>('delete',`${this.basePath}/calendar/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteMultipleCalendarEntities(body: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<Array<CalendarResponseDto>>;
    public deleteMultipleCalendarEntities(body: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CalendarResponseDto>>>;
    public deleteMultipleCalendarEntities(body: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CalendarResponseDto>>>;
    public deleteMultipleCalendarEntities(body: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling deleteMultipleCalendarEntities.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<CalendarResponseDto>>('post',`${this.basePath}/calendar/batchDelete`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Obtain all entries from the provided user
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllCalendarEntities(observe?: 'body', reportProgress?: boolean): Observable<Array<CalendarResponseDto>>;
    public getAllCalendarEntities(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CalendarResponseDto>>>;
    public getAllCalendarEntities(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CalendarResponseDto>>>;
    public getAllCalendarEntities(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CalendarResponseDto>>('get',`${this.basePath}/calendar`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Ottieni tutte le richieste in base al ruolo utente: admin, owner
     * @param pageable 
     * @param tab 
     * @param types 
     * @param users 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllRequests(pageable: Pageable, tab: string, types?: Array<string>, users?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<PagedResponseUserRequestResponseDto>;
    public getAllRequests(pageable: Pageable, tab: string, types?: Array<string>, users?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PagedResponseUserRequestResponseDto>>;
    public getAllRequests(pageable: Pageable, tab: string, types?: Array<string>, users?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PagedResponseUserRequestResponseDto>>;
    public getAllRequests(pageable: Pageable, tab: string, types?: Array<string>, users?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pageable === null || pageable === undefined) {
            throw new Error('Required parameter pageable was null or undefined when calling getAllRequests.');
        }

        if (tab === null || tab === undefined) {
            throw new Error('Required parameter tab was null or undefined when calling getAllRequests.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageable !== undefined && pageable !== null) {
            queryParameters = queryParameters.set('pageable', <any>pageable);
        }
        if (types) {
            types.forEach((element) => {
                queryParameters = queryParameters.append('types', <any>element);
            })
        }
        if (users) {
            users.forEach((element) => {
                queryParameters = queryParameters.append('users', <any>element);
            })
        }
        if (tab !== undefined && tab !== null) {
            queryParameters = queryParameters.set('tab', <any>tab);
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PagedResponseUserRequestResponseDto>('get',`${this.basePath}/calendar/requests`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Obtain all user calendar entries from specific month and year
     * @param month 
     * @param year 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCalendarEntitiesByMonthYear(month: string, year: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CalendarResponseDto>>;
    public getCalendarEntitiesByMonthYear(month: string, year: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CalendarResponseDto>>>;
    public getCalendarEntitiesByMonthYear(month: string, year: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CalendarResponseDto>>>;
    public getCalendarEntitiesByMonthYear(month: string, year: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (month === null || month === undefined) {
            throw new Error('Required parameter month was null or undefined when calling getCalendarEntitiesByMonthYear.');
        }

        if (year === null || year === undefined) {
            throw new Error('Required parameter year was null or undefined when calling getCalendarEntitiesByMonthYear.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (month !== undefined && month !== null) {
            queryParameters = queryParameters.set('month', <any>month);
        }
        if (year !== undefined && year !== null) {
            queryParameters = queryParameters.set('year', <any>year);
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CalendarResponseDto>>('get',`${this.basePath}/calendar/byMonthYear`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Ottieni tutte le tue richieste
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOpenClosedRequestsNumber(observe?: 'body', reportProgress?: boolean): Observable<OpenClosedRequestNumberResponse>;
    public getOpenClosedRequestsNumber(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OpenClosedRequestNumberResponse>>;
    public getOpenClosedRequestsNumber(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OpenClosedRequestNumberResponse>>;
    public getOpenClosedRequestsNumber(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<OpenClosedRequestNumberResponse>('get',`${this.basePath}/calendar/requests/split-count`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Ottieni tutte le tue richieste
     * @param pageable 
     * @param tab 
     * @param types 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUserRequests(pageable: Pageable, tab: string, types?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<PagedResponseUserRequestResponseDto>;
    public getUserRequests(pageable: Pageable, tab: string, types?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PagedResponseUserRequestResponseDto>>;
    public getUserRequests(pageable: Pageable, tab: string, types?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PagedResponseUserRequestResponseDto>>;
    public getUserRequests(pageable: Pageable, tab: string, types?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pageable === null || pageable === undefined) {
            throw new Error('Required parameter pageable was null or undefined when calling getUserRequests.');
        }

        if (tab === null || tab === undefined) {
            throw new Error('Required parameter tab was null or undefined when calling getUserRequests.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageable !== undefined && pageable !== null) {
            queryParameters = queryParameters.set('pageable', <any>pageable);
        }
        if (types) {
            types.forEach((element) => {
                queryParameters = queryParameters.append('types', <any>element);
            })
        }
        if (tab !== undefined && tab !== null) {
            queryParameters = queryParameters.set('tab', <any>tab);
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PagedResponseUserRequestResponseDto>('get',`${this.basePath}/calendar/my-requests`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Save a new calendar entry
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveCalendarEntity(body: SaveCalendarEntityRequestDto, observe?: 'body', reportProgress?: boolean): Observable<CalendarResponseDto>;
    public saveCalendarEntity(body: SaveCalendarEntityRequestDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CalendarResponseDto>>;
    public saveCalendarEntity(body: SaveCalendarEntityRequestDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CalendarResponseDto>>;
    public saveCalendarEntity(body: SaveCalendarEntityRequestDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling saveCalendarEntity.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CalendarResponseDto>('post',`${this.basePath}/calendar`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Save calendar entries in bulk
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveMultipleCalendarEntities(body: Array<SaveCalendarEntityRequestDto>, observe?: 'body', reportProgress?: boolean): Observable<Array<CalendarResponseDto>>;
    public saveMultipleCalendarEntities(body: Array<SaveCalendarEntityRequestDto>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CalendarResponseDto>>>;
    public saveMultipleCalendarEntities(body: Array<SaveCalendarEntityRequestDto>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CalendarResponseDto>>>;
    public saveMultipleCalendarEntities(body: Array<SaveCalendarEntityRequestDto>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling saveMultipleCalendarEntities.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<CalendarResponseDto>>('post',`${this.basePath}/calendar/bulk`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateCalendarEntities(body: Array<CalendarEntity>, observe?: 'body', reportProgress?: boolean): Observable<Array<CalendarResponseDto>>;
    public updateCalendarEntities(body: Array<CalendarEntity>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CalendarResponseDto>>>;
    public updateCalendarEntities(body: Array<CalendarEntity>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CalendarResponseDto>>>;
    public updateCalendarEntities(body: Array<CalendarEntity>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateCalendarEntities.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<CalendarResponseDto>>('post',`${this.basePath}/calendar/batchUpdate`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateCalendarEntity(body: CalendarEntity, id: string, observe?: 'body', reportProgress?: boolean): Observable<CalendarResponseDto>;
    public updateCalendarEntity(body: CalendarEntity, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CalendarResponseDto>>;
    public updateCalendarEntity(body: CalendarEntity, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CalendarResponseDto>>;
    public updateCalendarEntity(body: CalendarEntity, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateCalendarEntity.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateCalendarEntity.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CalendarResponseDto>('put',`${this.basePath}/calendar/${encodeURIComponent(String(id))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Aggiorna lo stato di una richiesta. Accettandola o rifiutandola
     * @param action 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateRequestStatus(action: ApprovalAction, id: string, observe?: 'body', reportProgress?: boolean): Observable<BooleanResponse>;
    public updateRequestStatus(action: ApprovalAction, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BooleanResponse>>;
    public updateRequestStatus(action: ApprovalAction, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BooleanResponse>>;
    public updateRequestStatus(action: ApprovalAction, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (action === null || action === undefined) {
            throw new Error('Required parameter action was null or undefined when calling updateRequestStatus.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateRequestStatus.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (action !== undefined && action !== null) {
            queryParameters = queryParameters.set('action', <any>action);
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<BooleanResponse>('put',`${this.basePath}/calendar/requests/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
