/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Azione di approvazione eseguibile su una richiesta (usata dagli admin e owner)
 */
export type ApprovalAction = 'ACCEPT' | 'REJECT';

export const ApprovalAction = {
    ACCEPT: 'ACCEPT' as ApprovalAction,
    REJECT: 'REJECT' as ApprovalAction
};