/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CalendarAvailabilityEntry } from './calendarAvailabilityEntry';
import { CalendarRequestEntry } from './calendarRequestEntry';
import { CalendarWorkingDayEntry } from './calendarWorkingDayEntry';
import { CalendarWorkingTripEntry } from './calendarWorkingTripEntry';

/**
 * Interfaccia base per le varie entry del calendario
 */
export type CalendarEntry = CalendarRequestEntry | CalendarWorkingDayEntry | CalendarAvailabilityEntry | CalendarWorkingTripEntry;