/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Rappresenta una entry di una richiesta nel calendario
 */
export interface CalendarRequestEntry { 
    requestType?: string;
    dateFrom?: Date;
    dateTo?: Date;
    timeFrom?: string;
    timeTo?: string;
    status?: CalendarRequestEntry.StatusEnum;
}
export namespace CalendarRequestEntry {
    export type StatusEnum = 'PENDING' | 'ACCEPTED' | 'REJECTED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        ACCEPTED: 'ACCEPTED' as StatusEnum,
        REJECTED: 'REJECTED' as StatusEnum
    };
}