/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Project { 
    id?: string;
    name?: string;
    description?: string;
    status?: Project.StatusEnum;
    assignedTo?: Array<string>;
}
export namespace Project {
    export type StatusEnum = 'CREATED' | 'IN_PROGRESS' | 'COMPLETED';
    export const StatusEnum = {
        CREATED: 'CREATED' as StatusEnum,
        INPROGRESS: 'IN_PROGRESS' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum
    };
}