/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserBasicDetailsResponse { 
    name?: string;
    surname?: string;
    email?: string;
    duty?: string;
    role?: UserBasicDetailsResponse.RoleEnum;
}
export namespace UserBasicDetailsResponse {
    export type RoleEnum = 'USER' | 'ADMIN' | 'OWNER';
    export const RoleEnum = {
        USER: 'USER' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum,
        OWNER: 'OWNER' as RoleEnum
    };
}