/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './grantedAuthority';

export interface User { 
    id?: string;
    email?: string;
    pwd?: string;
    name?: string;
    surname?: string;
    serialNum?: number;
    duty?: string;
    employmentType?: string;
    hireDate?: Date;
    iban?: number;
    birthDate?: Date;
    address?: string;
    phone?: string;
    role?: User.RoleEnum;
    password?: string;
    enabled?: boolean;
    username?: string;
    authorities?: Array<GrantedAuthority>;
    accountNonExpired?: boolean;
    credentialsNonExpired?: boolean;
    accountNonLocked?: boolean;
}
export namespace User {
    export type RoleEnum = 'USER' | 'ADMIN';
    export const RoleEnum = {
        USER: 'USER' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum
    };
}