/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserProfile { 
    name?: string;
    surname?: string;
    email?: string;
    serialNum?: number;
    duty?: string;
    employmentType?: string;
    hireDate?: Date;
    birthDate?: Date;
    address?: string;
    phone?: string;
    iban?: number;
    role?: UserProfile.RoleEnum;
}
export namespace UserProfile {
    export type RoleEnum = 'USER' | 'ADMIN';
    export const RoleEnum = {
        USER: 'USER' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum
    };
}