/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserData { 
    assignedProjects?: Array<string>;
    annualLeaveHours?: number;
    annualPermitHours?: number;
    dailyHours?: number;
}