/**
 * API Presenze-Pro
 * API used by the Presenze-Pro thesis project’s client
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserRequestResponseDto { 
    id?: string;
    userEmail?: string;
    type?: UserRequestResponseDto.TypeEnum;
    dateFrom?: Date;
    dateTo?: Date;
    status?: UserRequestResponseDto.StatusEnum;
}
export namespace UserRequestResponseDto {
    export type TypeEnum = 'FERIE' | 'MALATTIA' | 'TRASFERTA' | 'PERMESSI' | 'CONGEDO';
    export const TypeEnum = {
        FERIE: 'FERIE' as TypeEnum,
        MALATTIA: 'MALATTIA' as TypeEnum,
        TRASFERTA: 'TRASFERTA' as TypeEnum,
        PERMESSI: 'PERMESSI' as TypeEnum,
        CONGEDO: 'CONGEDO' as TypeEnum
    };
    export type StatusEnum = 'PENDING' | 'ACCEPTED' | 'REJECTED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        ACCEPTED: 'ACCEPTED' as StatusEnum,
        REJECTED: 'REJECTED' as StatusEnum
    };
}